// XIOM Package Registry -- OIDC canary publish (staging proof).
// Copyright (c) 2026 Eleftherios Notas and The XIOM Authors
// SPDX-License-Identifier: MIT OR Apache-2.0
//
// Publishes one tiny signed package through a real GitHub OIDC token to a
// registry, then reads back the recorded provenance. Used by
// .github/workflows/oidc-canary.yml against staging: it needs no compiler
// release and no registry secret, only the JWT minted in the workflow.
//
// Environment:
//   XIOM_REGISTRY            base URL (required)
//   XIOM_REGISTRY_TOKEN      the OIDC JWT (required)
//   CANARY_PACKAGE           package name (default xiom.canary-oidc)
//   CANARY_VERSION           version (default 0.0.0-canary.<epoch>)
//   CANARY_EXPECT_REPOSITORY expected publisher repository
//                            (default xiom-lang/registry)

'use strict';

const crypto = require('crypto');
const { execFileSync } = require('child_process');
const fs = require('fs');
const os = require('os');
const path = require('path');

function fail(message) {
  console.error(`canary: FAIL: ${message}`);
  process.exit(1);
}

function requiredEnv(name) {
  const value = process.env[name];
  if (!value || !value.trim()) fail(`${name} is required`);
  return value.trim();
}

function manifest(pkg, version) {
  return `// OIDC canary fixture -- generated by scripts/oidc-canary.js
package canary {
  name: "${pkg}";
  version: "${version}";
  description: "OIDC trusted-publishing canary";
  categories: ["tooling"];
  license: "MIT OR Apache-2.0";
}
`;
}

function buildTarball(dir, pkg, version) {
  fs.writeFileSync(path.join(dir, 'package.xi'), manifest(pkg, version));
  const out = path.join(dir, 'package.tar.gz');
  execFileSync('tar', ['-czf', out, '-C', dir, 'package.xi'], { stdio: 'inherit' });
  return fs.readFileSync(out);
}

function sign(bytes) {
  const { privateKey, publicKey } = crypto.generateKeyPairSync('ed25519');
  const der = publicKey.export({ format: 'der', type: 'spki' });
  const publicKeyHex = der.subarray(der.length - 32).toString('hex');
  const signature = crypto.sign(null, bytes, privateKey).toString('hex');
  return { signature, publicKeyHex };
}

async function main() {
  const registry = requiredEnv('XIOM_REGISTRY').replace(/\/+$/, '');
  const token = requiredEnv('XIOM_REGISTRY_TOKEN');
  const pkg = (process.env.CANARY_PACKAGE || 'xiom.canary-oidc').trim();
  const version = (process.env.CANARY_VERSION || `0.0.0-canary.${Date.now()}`).trim();
  const expectRepository = (process.env.CANARY_EXPECT_REPOSITORY || 'xiom-lang/registry').trim();

  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'xiom-canary-'));
  let bytes;
  try {
    bytes = buildTarball(dir, pkg, version);
  } finally {
    fs.rmSync(dir, { recursive: true, force: true });
  }
  const { signature, publicKeyHex } = sign(bytes);

  const form = new FormData();
  form.set('name', pkg);
  form.set('version', version);
  form.set('signature', signature);
  form.set('publicKey', publicKeyHex);
  form.set('package', new Blob([bytes], { type: 'application/gzip' }), 'package.tar.gz');

  console.log(`canary: publishing ${pkg}@${version} to ${registry}`);
  const publishResponse = await fetch(`${registry}/publish`, {
    method: 'POST',
    body: form,
    headers: { Authorization: `Bearer ${token}` },
  });
  const publishBody = await publishResponse.text();
  if (publishResponse.status !== 201) {
    fail(`publish returned ${publishResponse.status}: ${publishBody}`);
  }
  console.log(`canary: publish OK: ${publishBody}`);

  const packageResponse = await fetch(`${registry}/packages/${encodeURIComponent(pkg)}`, {
    headers: { Accept: '*/*' },
  });
  if (!packageResponse.ok) {
    fail(`read-back returned ${packageResponse.status}`);
  }
  const stored = (await packageResponse.json()).versions?.[version];
  const publisher = stored?.publisher;
  if (!publisher) fail('stored version has no publisher provenance');

  console.log(`canary: publisher ${JSON.stringify(publisher)}`);
  if (publisher.repository !== expectRepository) {
    fail(`publisher.repository is "${publisher.repository}", expected "${expectRepository}"`);
  }
  if (!publisher.runUrl || !publisher.runUrl.startsWith(`https://github.com/${expectRepository}/actions/runs/`)) {
    fail(`publisher.runUrl is not a run URL for ${expectRepository}: ${publisher.runUrl}`);
  }
  console.log(`canary: OK -- ${pkg}@${version} carries provenance from ${publisher.repository}`);
}

main().catch((err) => fail(err && err.stack ? err.stack : String(err)));
